### ISSUE TITLE
set userId at client level

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-analytics-android#3]
for simplicity analytics clients should have a `setUserId` method. Impressions and Engagement events should get the userId value from the client. see iOS and JS docs here: http://getstream.io/docs_analytics/

**Comment by appsoluut** [comment]
Added support for global userId.

Updated this info in the README file

``` java
    StreamAnalyticsAuth auth = new StreamAnalyticsAuth(API_KEY, API_TOKEN);

    StreamAnalytics client = StreamAnalytics.getInstance(auth);
    client.setUserId("486892");
```

You can still override the userId per Impression or Engagement event if you supply `withUserId()` to the event builder.
